version: '3.5'
services:
  web:
    environment:
      - NODE_ENV=staging
      - API_URL=http://api.localhost
  api:
    build:
      args:
        - NODE_ENV=staging
    environment:
      - NODE_ENV=staging
  db:
    command: "--smallfiles --logpath=/dev/null"
