version: '3.5'
services:
  nginx:
    restart: unless-stopped
  web:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=https://api.poland20.com
  api:
    environment:
      - NODE_ENV=production
    restart: unless-stopped