version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '9009:9009'
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data: