version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: poland20/p20-website
    container_name: p20-website
    depends_on:
      - db
  db:
    image: mongo
    container_name: p20-db
    volumes:
      - data:/data/db
volumes:
  data: